In [1]:
import pandas as pd
from datetime import datetime

In [2]:
RUN_ID = "run_test_001"

yellow_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet"
green_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2024-01.parquet"

yellow_df = pd.read_parquet(yellow_url)
green_df = pd.read_parquet(green_url)

In [3]:
print("YELLOW SHAPE:", yellow_df.shape)
print("GREEN SHAPE:", green_df.shape)

YELLOW SHAPE: (2964624, 19)
GREEN SHAPE: (56551, 20)

In [4]:
print("YELLOW COLUMNS")
print(yellow_df.columns.tolist())

YELLOW COLUMNS
['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'Airport_fee']

In [5]:
print("\nGREEN COLUMNS")
print(green_df.columns.tolist())

GREEN COLUMNS
['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime', 'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID', 'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge', 'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge']

In [6]:
print("YELLOW DTYPES")
print(yellow_df.dtypes)

print("\nGREEN DTYPES")
print(green_df.dtypes)

YELLOW DTYPES
VendorID                          int32
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
dtype: object

GREEN DTYPES
VendorID                          int32
lpep_pickup_datetime     datetime64[ns]
lpep_dropoff_datetime    datetime64[ns]
store_and_fwd_flag               object
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
dtype: object

In [7]:
yellow_df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.7,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.0,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.3,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.0,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.0
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.9,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.0

In [8]:
green_df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2024-01-01 00:46:55,2024-01-01 00:58:25,N,1.0,236,239,1.0,1.98,12.8,1.0,0.5,3.61,0.0,NaN,1.0,21.66,1.0,1.0,2.75
1,2,2024-01-01 00:31:42,2024-01-01 00:52:34,N,1.0,65,170,5.0,6.54,30.3,1.0,0.5,7.11,0.0,NaN,1.0,42.66,1.0,1.0,2.75
2,2,2024-01-01 00:30:21,2024-01-01 00:49:23,N,1.0,74,262,1.0,3.08,19.8,1.0,0.5,3.00,0.0,NaN,1.0,28.05,1.0,1.0,2.75
3,1,2024-01-01 00:30:20,2024-01-01 00:42:12,N,1.0,74,116,1.0,2.40,14.2,1.0,1.5,0.00,0.0,NaN,1.0,16.70,2.0,1.0,0.00
4,2,2024-01-01 00:32:38,2024-01-01 00:43:37,N,1.0,74,243,1.0,5.14,22.6,1.0,0.5,6.28,0.0,NaN,1.0,31.38,1.0,1.0,0.00

In [17]:
yellow_std = yellow_df.rename(columns={
    "VendorID": "vendor_id",
    "tpep_pickup_datetime": "pickup_datetime",
    "tpep_dropoff_datetime": "dropoff_datetime",
    "RatecodeID": "rate_code_id",
    "PULocationID": "pu_location_id",
    "DOLocationID": "do_location_id",
    "Airport_fee": "airport_fee",
})

yellow_std["payment_type"] = yellow_std["payment_type"].astype(float)

yellow_std["run_id"] = RUN_ID
yellow_std["source_year"] = 2024
yellow_std["source_month"] = 1
yellow_std["service_type"] = "yellow"
yellow_std["ingested_at_utc"] = pd.Timestamp.utcnow().tz_localize(None)

yellow_std = yellow_std[[
    "vendor_id",
    "pickup_datetime",
    "dropoff_datetime",
    "passenger_count",
    "trip_distance",
    "rate_code_id",
    "store_and_fwd_flag",
    "pu_location_id",
    "do_location_id",
    "payment_type",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee",
    "run_id",
    "source_year",
    "source_month",
    "service_type",
    "ingested_at_utc"
]]

In [18]:
yellow_std.head()

,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,rate_code_id,store_and_fwd_flag,pu_location_id,do_location_id,payment_type,...,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,run_id,source_year,source_month,service_type,ingested_at_utc
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2.0,...,0.0,1.0,22.70,2.5,0.0,run_test_001,2024,1,yellow,2026-04-01 04:22:30.743839
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1.0,...,0.0,1.0,18.75,2.5,0.0,run_test_001,2024,1,yellow,2026-04-01 04:22:30.743839
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1.0,...,0.0,1.0,31.30,2.5,0.0,run_test_001,2024,1,yellow,2026-04-01 04:22:30.743839
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1.0,...,0.0,1.0,17.00,2.5,0.0,run_test_001,2024,1,yellow,2026-04-01 04:22:30.743839
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1.0,...,0.0,1.0,16.10,2.5,0.0,run_test_001,2024,1,yellow,2026-04-01 04:22:30.743839

In [19]:
yellow_std.dtypes

vendor_id                         int32
pickup_datetime          datetime64[ns]
dropoff_datetime         datetime64[ns]
passenger_count                 float64
trip_distance                   float64
rate_code_id                    float64
store_and_fwd_flag               object
pu_location_id                    int32
do_location_id                    int32
payment_type                    float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
run_id                           object
source_year                       int64
source_month                      int64
service_type                     object
ingested_at_utc          datetime64[ns]
dtype: object

In [20]:
green_std = green_df.rename(columns={
    "VendorID": "vendor_id",
    "lpep_pickup_datetime": "pickup_datetime",
    "lpep_dropoff_datetime": "dropoff_datetime",
    "RatecodeID": "rate_code_id",
    "PULocationID": "pu_location_id",
    "DOLocationID": "do_location_id",
})

green_std["payment_type"] = green_std["payment_type"].astype(float)

green_std["run_id"] = RUN_ID
green_std["source_year"] = 2024
green_std["source_month"] = 1
green_std["service_type"] = "green"
green_std["ingested_at_utc"] = pd.Timestamp.utcnow().tz_localize(None)

green_std = green_std[[
    "vendor_id",
    "pickup_datetime",
    "dropoff_datetime",
    "store_and_fwd_flag",
    "rate_code_id",
    "pu_location_id",
    "do_location_id",
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "ehail_fee",
    "improvement_surcharge",
    "total_amount",
    "payment_type",
    "trip_type",
    "congestion_surcharge",
    "run_id",
    "source_year",
    "source_month",
    "service_type",
    "ingested_at_utc"
]]

In [21]:
green_std.head()

,vendor_id,pickup_datetime,dropoff_datetime,store_and_fwd_flag,rate_code_id,pu_location_id,do_location_id,passenger_count,trip_distance,fare_amount,...,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,run_id,source_year,source_month,service_type,ingested_at_utc
0,2,2024-01-01 00:46:55,2024-01-01 00:58:25,N,1.0,236,239,1.0,1.98,12.8,...,1.0,21.66,1.0,1.0,2.75,run_test_001,2024,1,green,2026-04-01 04:22:32.371048
1,2,2024-01-01 00:31:42,2024-01-01 00:52:34,N,1.0,65,170,5.0,6.54,30.3,...,1.0,42.66,1.0,1.0,2.75,run_test_001,2024,1,green,2026-04-01 04:22:32.371048
2,2,2024-01-01 00:30:21,2024-01-01 00:49:23,N,1.0,74,262,1.0,3.08,19.8,...,1.0,28.05,1.0,1.0,2.75,run_test_001,2024,1,green,2026-04-01 04:22:32.371048
3,1,2024-01-01 00:30:20,2024-01-01 00:42:12,N,1.0,74,116,1.0,2.40,14.2,...,1.0,16.70,2.0,1.0,0.00,run_test_001,2024,1,green,2026-04-01 04:22:32.371048
4,2,2024-01-01 00:32:38,2024-01-01 00:43:37,N,1.0,74,243,1.0,5.14,22.6,...,1.0,31.38,1.0,1.0,0.00,run_test_001,2024,1,green,2026-04-01 04:22:32.371048

In [22]:
green_std.dtypes

vendor_id                         int32
pickup_datetime          datetime64[ns]
dropoff_datetime         datetime64[ns]
store_and_fwd_flag               object
rate_code_id                    float64
pu_location_id                    int32
do_location_id                    int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
run_id                           object
source_year                       int64
source_month                      int64
service_type                     object
ingested_at_utc          datetime64[ns]
dtype: object

In [24]:
!pip install -U "snowflake-connector-python[pandas]" "pyarrow>=14.0.1"

Requirement already satisfied: snowflake-connector-python[pandas] in /opt/conda/lib/python3.11/site-packages (4.4.0)
Requirement already satisfied: pyarrow>=14.0.1 in /opt/conda/lib/python3.11/site-packages (23.0.1)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (1.5.1)
Requirement already satisfied: cryptography>=46.0.5 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (46.0.6)
Requirement already satisfied: pyOpenSSL>=24.0.0 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (26.0.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (2.12.1)
Requirement already satisfied: pytz in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (2023.3.post1)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (2.33.1)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (23.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (3.2.0)
Requirement already satisfied: idna<4,>=3.7 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (3.11)
Requirement already satisfied: certifi>=2024.7.4 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (2026.2.25)
Requirement already satisfied: typing_extensions<5,>=4.3 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (3.25.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (3.10.0)
Requirement already satisfied: tomlkit in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (0.14.0)
Requirement already satisfied: boto3>=1.24 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (1.42.79)
Requirement already satisfied: botocore>=1.24 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (1.42.79)
Requirement already satisfied: pandas<3.0.0,>=1.0.0 in /opt/conda/lib/python3.11/site-packages (from snowflake-connector-python[pandas]) (1.5.3)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from boto3>=1.24->snowflake-connector-python[pandas]) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.11/site-packages (from boto3>=1.24->snowflake-connector-python[pandas]) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.11/site-packages (from botocore>=1.24->snowflake-connector-python[pandas]) (2.8.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.11/site-packages (from botocore>=1.24->snowflake-connector-python[pandas]) (2.0.4)
Requirement already satisfied: cffi>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from cryptography>=46.0.5->snowflake-connector-python[pandas]) (2.0.0)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.11/site-packages (from pandas<3.0.0,>=1.0.0->snowflake-connector-python[pandas]) (1.24.4)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python[pandas]) (2.21)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python[pandas]) (1.16.0)

In [23]:
import os
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

conn = snowflake.connector.connect(
    user=os.getenv("SNOWFLAKE_USER"),
    password=os.getenv("SNOWFLAKE_PASSWORD"),
    account=os.getenv("SNOWFLAKE_ACCOUNT"),
    warehouse=os.getenv("SNOWFLAKE_WAREHOUSE"),
    database=os.getenv("SNOWFLAKE_DATABASE"),
    schema=os.getenv("SNOWFLAKE_SCHEMA_RAW"),
    role=os.getenv("SNOWFLAKE_ROLE"),
)

In [25]:
#esto luego se cambia a solo yellow_std para ocupar todos los datos, head(1000) es para pruebas
yellow_sample = yellow_std.head(1000).copy()

success, nchunks, nrows, _ = write_pandas(
    conn,
    yellow_sample,
    "YELLOW_TRIPS_RAW",
    database=os.getenv("SNOWFLAKE_DATABASE"),
    schema=os.getenv("SNOWFLAKE_SCHEMA_RAW"),
    auto_create_table=False,
    overwrite=False,
    quote_identifiers=False,
    use_logical_type=True
)

print("SUCCESS:", success)
print("CHUNKS:", nchunks)
print("ROWS WRITTEN:", nrows)

SUCCESS: True
CHUNKS: 1
ROWS WRITTEN: 1000

In [26]:
cur = conn.cursor()

cur.execute("SELECT COUNT(*) FROM YELLOW_TRIPS_RAW")
print(cur.fetchone())

cur.execute("""
SELECT vendor_id, pickup_datetime, dropoff_datetime, total_amount, service_type
FROM YELLOW_TRIPS_RAW
LIMIT 5
""")
print(cur.fetchall())

(1000,)
[(2, datetime.datetime(2024, 1, 1, 0, 57, 55), datetime.datetime(2024, 1, 1, 1, 17, 43), 22.7, 'yellow'), (1, datetime.datetime(2024, 1, 1, 0, 3), datetime.datetime(2024, 1, 1, 0, 9, 36), 18.75, 'yellow'), (1, datetime.datetime(2024, 1, 1, 0, 17, 6), datetime.datetime(2024, 1, 1, 0, 35, 1), 31.3, 'yellow'), (1, datetime.datetime(2024, 1, 1, 0, 36, 38), datetime.datetime(2024, 1, 1, 0, 44, 56), 17.0, 'yellow'), (1, datetime.datetime(2024, 1, 1, 0, 46, 51), datetime.datetime(2024, 1, 1, 0, 52, 57), 16.1, 'yellow')]

In [27]:
#esto luego se cambia a solo green_std para ocupar todos los datos, head(1000) es para pruebas
green_sample = green_std.head(1000).copy() 

success, nchunks, nrows, _ = write_pandas(
    conn,
    green_sample,
    "GREEN_TRIPS_RAW",
    database=os.getenv("SNOWFLAKE_DATABASE"),
    schema=os.getenv("SNOWFLAKE_SCHEMA_RAW"),
    auto_create_table=False,
    overwrite=False,
    quote_identifiers=False,
    use_logical_type=True
)

print("SUCCESS:", success)
print("CHUNKS:", nchunks)
print("ROWS WRITTEN:", nrows)

SUCCESS: True
CHUNKS: 1
ROWS WRITTEN: 1000

In [28]:
cur.execute("SELECT COUNT(*) FROM GREEN_TRIPS_RAW")
print(cur.fetchone())

cur.execute("""
SELECT vendor_id, pickup_datetime, dropoff_datetime, total_amount, service_type
FROM GREEN_TRIPS_RAW
LIMIT 5
""")
print(cur.fetchall())

(1000,)
[(2, datetime.datetime(2024, 1, 1, 0, 46, 55), datetime.datetime(2024, 1, 1, 0, 58, 25), 21.66, 'green'), (2, datetime.datetime(2024, 1, 1, 0, 31, 42), datetime.datetime(2024, 1, 1, 0, 52, 34), 42.66, 'green'), (2, datetime.datetime(2024, 1, 1, 0, 30, 21), datetime.datetime(2024, 1, 1, 0, 49, 23), 28.05, 'green'), (1, datetime.datetime(2024, 1, 1, 0, 30, 20), datetime.datetime(2024, 1, 1, 0, 42, 12), 16.7, 'green'), (2, datetime.datetime(2024, 1, 1, 0, 32, 38), datetime.datetime(2024, 1, 1, 0, 43, 37), 31.38, 'green')]

In [29]:
cur.close()
conn.close()

In [30]:
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("Spark Snowflake Test")
    .master("local[*]")
    .config(
        "spark.jars.packages",
        ",".join([
            "net.snowflake:spark-snowflake_2.12:2.12.0-spark_3.4",
            "net.snowflake:snowflake-jdbc:3.14.4"
        ])
    )
    .getOrCreate()
)

In [31]:
import os

sfOptions = {
    "sfURL": f"{os.getenv('SNOWFLAKE_ACCOUNT')}.snowflakecomputing.com",
    "sfUser": os.getenv("SNOWFLAKE_USER"),
    "sfPassword": os.getenv("SNOWFLAKE_PASSWORD"),
    "sfDatabase": os.getenv("SNOWFLAKE_DATABASE"),
    "sfSchema": os.getenv("SNOWFLAKE_SCHEMA_RAW"),
    "sfWarehouse": os.getenv("SNOWFLAKE_WAREHOUSE"),
    "sfRole": os.getenv("SNOWFLAKE_ROLE"),
}

In [32]:
sf_test = (
    spark.read
    .format("snowflake")
    .options(**sfOptions)
    .option("query", "SELECT CURRENT_VERSION() AS VERSION")
    .load()
)

sf_test.show()

+-------+
|VERSION|
+-------+
|10.11.1|
+-------+